# Generated by Django 3.2.16 on 2023-02-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Ticks', models.IntegerField(max_length=5)),
                ('RelativePriceChange', models.DecimalField(decimal_places=5, max_digits=20)),
                ('TotalPriceChange', models.DecimalField(decimal_places=5, max_digits=20)),
                ('VolumeChange', models.DecimalField(decimal_places=5, max_digits=20)),
                ('LastPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('LastVolume', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
