# Generated by Django 3.2.16 on 2023-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trade', '0003_auto_20230208_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInfo_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Ticks', models.IntegerField()),
                ('RelativePriceChange', models.DecimalField(decimal_places=5, max_digits=20)),
                ('TotalPriceChange', models.DecimalField(decimal_places=5, max_digits=20)),
                ('VolumeChange', models.DecimalField(decimal_places=5, max_digits=20)),
                ('LastPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('LastVolume', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
        
    ]
